name: Build, Deploy and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        font:
          - { key: all, suffix: '' }
          - { key: cdn, suffix: '-cdn-fonts' }
          - { key: firasans, suffix: '-firasans-only' }
          - { key: misans, suffix: '-misans-only' }
          - { key: pingfang, suffix: '-pingfang-only' }
          - { key: sarasa, suffix: '-sarasa-only' }
          - { key: none, suffix: '-no-fonts' }
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: pnpm/action-setup@v6

      - name: Install and Build 🔧
        env:
          FONT: ${{ matrix.font.key }}
        run: |
          pnpm i
          pnpm run build
          echo 'zash.zend.eu.org' > ./dist/CNAME
          zip -r dist${{ matrix.font.suffix }}.zip dist

      - name: Deploy to Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages${{ matrix.font.suffix }}
          force_orphan: true

      - name: Upload to GitHub Release 📦
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v3.21.0
          name: v3.21.0
          files: dist${{ matrix.font.suffix }}.zip
          draft: false
          prerelease: false
